# Generated by Django 6.0.2 on 2026-02-22 07:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='films/actors/', verbose_name='Фото')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name': 'Актер',
                'verbose_name_plural': 'Актеры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('code', models.CharField(blank=True, max_length=2, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='films/directors/', verbose_name='Фото')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
            ],
            options={
                'verbose_name': 'Режиссер',
                'verbose_name_plural': 'Режиссеры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VideoSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('vk', 'VK Видео'), ('rutube', 'RuTube'), ('other', 'Другое')], max_length=20, verbose_name='Платформа')),
                ('url', models.URLField(verbose_name='Ссылка на видео')),
                ('embed_code', models.TextField(blank=True, verbose_name='HTML код для вставки')),
                ('youtube_id', models.CharField(blank=True, max_length=50, verbose_name='YouTube ID')),
                ('vk_id', models.CharField(blank=True, max_length=100, verbose_name='VK ID')),
                ('vk_owner_id', models.CharField(blank=True, max_length=50, verbose_name='VK Owner ID')),
                ('quality', models.CharField(default='HD', max_length=10, verbose_name='Качество')),
                ('language', models.CharField(default='Русский', max_length=50, verbose_name='Язык')),
                ('has_subtitles', models.BooleanField(default=True, verbose_name='С субтитрами')),
                ('has_sign_language', models.BooleanField(default=False, verbose_name='С жестовым переводом')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной источник')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Видеоисточник',
                'verbose_name_plural': 'Видеоисточники',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='film',
            name='director',
        ),
        migrations.RemoveField(
            model_name='film',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='film',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='film',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='film',
            name='video_url',
        ),
        migrations.AddField(
            model_name='film',
            name='age_rating',
            field=models.CharField(blank=True, max_length=10, verbose_name='Возрастной рейтинг'),
        ),
        migrations.AddField(
            model_name='film',
            name='backdrop',
            field=models.ImageField(blank=True, null=True, upload_to='films/backdrops/', verbose_name='Задний фон'),
        ),
        migrations.AddField(
            model_name='film',
            name='content_type',
            field=models.CharField(choices=[('movie', 'Фильм'), ('series', 'Сериал'), ('cartoon', 'Мультфильм'), ('anime', 'Аниме')], default='movie', max_length=20, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='film',
            name='episodes',
            field=models.IntegerField(default=1, verbose_name='Количество серий'),
        ),
        migrations.AddField(
            model_name='film',
            name='imdb_rating',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг IMDB'),
        ),
        migrations.AddField(
            model_name='film',
            name='kinopoisk_rating',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг Кинопоиск'),
        ),
        migrations.AddField(
            model_name='film',
            name='likes_count',
            field=models.IntegerField(default=0, verbose_name='Лайки'),
        ),
        migrations.AddField(
            model_name='film',
            name='original_title',
            field=models.CharField(blank=True, max_length=300, verbose_name='Оригинальное название'),
        ),
        migrations.AddField(
            model_name='film',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='films/posters/', verbose_name='Постер'),
        ),
        migrations.AddField(
            model_name='film',
            name='seasons',
            field=models.IntegerField(default=1, verbose_name='Количество сезонов'),
        ),
        migrations.AddField(
            model_name='film',
            name='short_description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='film',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='status',
            field=models.CharField(choices=[('announced', 'Анонсирован'), ('filming', 'Съемки'), ('released', 'Вышел'), ('ongoing', 'Выходит')], default='released', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='film',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AddField(
            model_name='film',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='film',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Добавлено'),
        ),
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='film',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Длительность (мин)'),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год'),
        ),
        migrations.AddField(
            model_name='film',
            name='actors',
            field=models.ManyToManyField(blank=True, to='films.actor', verbose_name='Актеры'),
        ),
        migrations.AddField(
            model_name='film',
            name='countries',
            field=models.ManyToManyField(blank=True, to='films.country', verbose_name='Страны'),
        ),
        migrations.AddField(
            model_name='film',
            name='directors',
            field=models.ManyToManyField(blank=True, to='films.director', verbose_name='Режиссеры'),
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(verbose_name='Сезон')),
                ('episode', models.IntegerField(verbose_name='Серия')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='Название серии')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Длительность (мин)')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Дата выхода')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes_list', to='films.film')),
            ],
            options={
                'verbose_name': 'Серия',
                'verbose_name_plural': 'Серии',
                'ordering': ['season', 'episode'],
            },
        ),
        migrations.CreateModel(
            name='FilmCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='films/collections/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('films', models.ManyToManyField(related_name='collections', to='films.film')),
            ],
            options={
                'verbose_name': 'Подборка',
                'verbose_name_plural': 'Подборки',
            },
        ),
        migrations.CreateModel(
            name='FilmRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='films.film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
        migrations.CreateModel(
            name='FilmReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='films.film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(blank=True, to='films.genre', verbose_name='Жанры'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['title'], name='films_film_title_72d7db_idx'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['year'], name='films_film_year_30d277_idx'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['content_type'], name='films_film_content_91a314_idx'),
        ),
        migrations.AddField(
            model_name='videosource',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='films.film'),
        ),
        migrations.AddField(
            model_name='episode',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='episodes', to='films.videosource'),
        ),
        migrations.AlterUniqueTogether(
            name='filmrating',
            unique_together={('film', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('film', 'season', 'episode')},
        ),
    ]
