# Generated by Django 6.0.2 on 2026-02-22 08:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_actor_country_director_genre_videosource_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videosource',
            options={'ordering': ['order', '-is_primary'], 'verbose_name': 'Видеоисточник', 'verbose_name_plural': 'Видеоисточники'},
        ),
        migrations.AddField(
            model_name='videosource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Добавлено'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videosource',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название источника'),
        ),
        migrations.AddField(
            model_name='videosource',
            name='video_file',
            field=models.FileField(blank=True, help_text='Загрузите видео файл (mp4, webm, etc.)', null=True, upload_to='films/videos/%Y/%m/', verbose_name='Видео файл'),
        ),
        migrations.AlterField(
            model_name='videosource',
            name='embed_code',
            field=models.TextField(blank=True, help_text='Вставьте iframe код с YouTube, VK, RuTube и т.д.', verbose_name='HTML код для вставки'),
        ),
        migrations.AlterField(
            model_name='videosource',
            name='language',
            field=models.CharField(blank=True, default='Русский', max_length=50, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='videosource',
            name='platform',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('vk', 'VK Видео'), ('rutube', 'RuTube'), ('local', 'Локальный файл'), ('iframe', 'Встроенный код'), ('other', 'Другое')], default='local', max_length=20, verbose_name='Платформа'),
        ),
        migrations.AlterField(
            model_name='videosource',
            name='quality',
            field=models.CharField(blank=True, default='HD', max_length=10, verbose_name='Качество'),
        ),
        migrations.AlterField(
            model_name='videosource',
            name='url',
            field=models.URLField(blank=True, verbose_name='Ссылка на видео'),
        ),
    ]
