# Generated by Django 6.0.2 on 2026-02-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('description', models.TextField(blank=True, verbose_name='Описание книги')),
                ('content', models.TextField(verbose_name='Текст книги')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('has_subtitles', models.BooleanField(default=False, verbose_name='Есть субтитры')),
                ('has_sign_language', models.BooleanField(default=False, verbose_name='Есть жестовый перевод')),
                ('has_audio_description', models.BooleanField(default=False, verbose_name='Есть аудиоописание')),
                ('tags', models.CharField(blank=True, max_length=300, verbose_name='Теги (через запятую)')),
                ('rating', models.FloatField(default=0.0, verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['-created_at'],
            },
        ),
    ]
