# Generated by Django 6.0.2 on 2026-02-21 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_comment_favorite_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Комментарий (старый)', 'verbose_name_plural': 'Комментарии (старые)'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Избранное (старое)', 'verbose_name_plural': 'Избранное (старое)'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Оценка (старая)', 'verbose_name_plural': 'Оценки (старые)'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_comments', to='books.book'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_favorites', to='books.book'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_ratings', to='books.book'),
        ),
    ]
