# Generated by Django 6.0.2 on 2026-02-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название курса')),
                ('instructor', models.CharField(max_length=100, verbose_name='Преподаватель')),
                ('description', models.TextField(verbose_name='Описание курса')),
                ('duration_hours', models.IntegerField(verbose_name='Продолжительность (часы)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('has_subtitles', models.BooleanField(default=True, verbose_name='Есть субтитры')),
                ('has_sign_language', models.BooleanField(default=False, verbose_name='Есть жестовый перевод')),
                ('has_audio_description', models.BooleanField(default=False, verbose_name='Есть аудиоописание')),
                ('has_transcript', models.BooleanField(default=True, verbose_name='Есть текстовая расшифровка')),
                ('tags', models.CharField(blank=True, max_length=300, verbose_name='Теги (через запятую)')),
                ('rating', models.FloatField(default=0.0, verbose_name='Рейтинг')),
                ('course_url', models.URLField(blank=True, verbose_name='Ссылка на курс')),
                ('platform', models.CharField(blank=True, max_length=100, verbose_name='Платформа')),
                ('level', models.CharField(choices=[('beginner', 'Начальный'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], default='beginner', max_length=20, verbose_name='Уровень')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['-created_at'],
            },
        ),
    ]
