# Generated by Django 6.0.2 on 2026-02-22 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='rating',
        ),
    ]
