# Generated by Django 6.0.2 on 2026-02-22 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_remove_course_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
