# Generated by Django 6.0.2 on 2026-02-21 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('average_rating', models.FloatField(default=0.0, verbose_name='Средний рейтинг')),
                ('review_count', models.PositiveIntegerField(default=0, verbose_name='Количество отзывов')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ['book', 'course', 'film']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Кэшированный рейтинг',
                'verbose_name_plural': 'Кэшированные рейтинги',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='reviews_cac_content_ad5a70_idx'), models.Index(fields=['average_rating'], name='reviews_cac_average_d911e0_idx')],
                'unique_together': {('content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ['book', 'course', 'film']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='reviews_fav_content_174ca9_idx'), models.Index(fields=['user', 'content_type'], name='reviews_fav_user_id_c776d1_idx')],
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Оценка')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('accessibility_subtitles', models.BooleanField(default=False, verbose_name='Субтитры доступны')),
                ('accessibility_sign_language', models.BooleanField(default=False, verbose_name='Жестовый перевод доступен')),
                ('accessibility_audio_description', models.BooleanField(default=False, verbose_name='Аудиоописание доступно')),
                ('accessibility_transcript', models.BooleanField(default=False, verbose_name='Текстовая расшифровка доступна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ['book', 'course', 'film']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='reviews_rev_content_627d80_idx'), models.Index(fields=['user', 'content_type'], name='reviews_rev_user_id_596571_idx')],
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
    ]
